### PR TITLE
Add documentation on makeprg

### PR DESCRIPTION
**Pull request by sol**

### CODE REVIEW

**Comment by sol** [comment]
@robbinch or @amarpotghan can one of you help with a section on Emacs?

**Comment by sol** [comment]
@soenkehahn In case you are not already using it, with `makeprg` you don't need a separate `Makefile` for every project.

**Comment by soenkehahn** [comment]
@sol: Thanks for the pointer.

Just to share how my workflow is atm: I edit the makefile very often, and have project-specific rules in there, so I prefer to have separate files for every project. I did set `makeprg` to `make -f geany` recently. To avoid file name clashes with projects that already have a Makefile. And put `geany` in my global gitignore file.

**Comment by amarpotghan** [comment]
@sol actually using the same Makefile and making with emacs (`M-x compile`) works perfectly. I will add it to README later.

**Pull request merged**
