### PR TITLE
Rename sensei-client to seito

### PR DESCRIPTION
**Pull request by sol**

### CODE REVIEW

**Comment by qoelet** [comment]
LVGTM :+1:

**Comment by soenkehahn** [comment]
I'm 50/50 on this change.

Most people probably don't know what `seito` is, and then it's very hard to remember the name. So I would suggest that we have an explanation in the readme that makes it easier to remember.

**Comment by sol** [comment]
@soenkehahn I would be more than happy to elaborate in the readme.  Can you come up with something and open a PR?

**Comment by soenkehahn** [comment]
Here you go: #24.

**Pull request merged**
